# The base image to use in the build.
# This is mandatory and must be the first command in the file.
FROM busybox:latest

# `Docker inspect` can be used to view image Labels.
LABEL version="1.0"
LABEL author="Bikram Kundu"

CMD ["echo", "Welcome to - Getting started with Docker"]
